import '../styles/globals.css'
import { Space_Grotesk } from 'next/font/google'
import { inter } from './(with-banner)/fonts'
import { Navigation } from '../components/Navigation'

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My first app with Next 13</title>
      </head>    

      <body className={spaceGrotesk.variable || inter.className}>
        <Navigation />
        <div style={{ padding: '1rem' }} >
          {children}
        </div>
      </body>
    </html>
  )
}
